### ISSUE TITLE
Scope simple API

### ISSUE THREAD

**Issue by MelanieAbraham** [openactive/data-model-validator#115]
Scoping designing a simple API around the validator, E.g. so that I can point to a document or feed and get validation results in a machine-readable format. I'd probably want some light-weight rate limiting around that

**Comment by petewalker** [comment]
The validator already works by calling the following URL:

```
POST https://validator.openactive.io/api/validateUrl/2.0
{
  "url": "https://activenewham-openactive.herokuapp.com/"
}
```

Responding with:

```
{
  "isRpdeFeed": true,
  "json": { ... }
  "response": [
    {
       "category": "internal",
       "message": "The JSON you have submitted appears to be an RPDE feed. For performance reasons, the validator has only checked the first 10 items in this feed. Please note that validation on RPDE feeds within the model validator is limited to checking whether required fields are present, and that the data in each item is a valid data model.",
       "path": "$",
       "rule": "RpdeFeedRule",
       "severity": "notice",
       "type": "found_rpde_feed",
       "value": { ... }
    },
    ...
  ]
}
```

* You can specify the version number you're validating against in the URL path
* The API will return all messages in the `response` key of the JSON returned

---

In the time left, I could create some rate limiting (with something like https://www.npmjs.com/package/express-rate-limit )? Otherwise, this endpoint is more-or-less good to go, @ldodds?

**Comment by petewalker** [comment]
Closed for now as scope has gone far enough.
