### ISSUE TITLE
priceCurrency is not required if price is zero

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#158]
`Required field "priceCurrency" is missing from "Offer".`

priceCurrency is not required if price is zero (still under discussion: https://github.com/openactive/open-booking-api/issues/54)

```
"offers": {
          "type": "Offer",
          "url": "https://www.letsride.co.uk/rides/mayor-of-londons-sky-ride/book",
          "price": 0
        },
```

**Comment by MelanieAbraham** [comment]
@ldodds is this making it into the spec?

**Comment by ldodds** [comment]
Yes, this should be in the booking spec.

**Comment by petewalker** [comment]
@ldodds @nickevansuk 

Note, whilst the booking-api spec has been updated, the current modelling spec editor's draft marks the `priceCurrency` as `REQUIRED` with no exceptions: https://github.com/openactive/modelling-opportunity-data/blob/aa12cc5/EditorsDraft/index.html#L2851

**Comment by petewalker** [comment]
It would be useful to know whether this property is `REQUIRED` with an exception or `OPTIONAL` with an exception, so that the change to data-models is consistent with the spec.

At the moment every time we have a field required in some circumstances, the field is marked as `OPTIONAL` in the data model, but rules are implemented as exceptions to that rule.
