### ISSUE TITLE
`startTime`/ `endTime` timezone validation

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#278]
Timezone is not valid as part of `startTime` or `endTime` as it does not make sense in this context. Values for these properties must be without timezone.

Error message: `"startTime" must not contain a timezone designator, and instead must be provided in local time based on the Event location.`

```
  "eventSchedule": [
    {
      "type": "Schedule",
      "startDate": "2018-01-01",
      "endDate": "2018-12-31",
      "repeatFrequency": "P1W",
      "byDay": [
        "http://schema.org/Friday"
      ],
      "startTime": "19:00Z",
      "endTime": "20:00Z"
    }
  ],
```

**Comment by petewalker** [comment]
I can add this message, but I've never actually understood your argument about timezone - it does actually make sense in this context - because there's a date range supplied.

This schedule will expand to:

* 2018-01-05T19:00:00Z
* 2018-01-12T19:00:00Z
* ...
* 2018-12-21T19:00:00Z
* 2018-12-28T19:00:00Z

If you wanted to vary it around DST, you could have 2 schedules with different start/end dates.

e.g.

```
"eventSchedule": [
    {
      "type": "Schedule",
      "startDate": "2018-01-01",
      "endDate": "2018-03-24",
      "repeatFrequency": "P1W",
      "byDay": [
        "http://schema.org/Friday"
      ],
      "startTime": "19:00Z",
      "endTime": "20:00Z"
    },
    {
      "type": "Schedule",
      "startDate": "2018-03-25",
      "endDate": "2018-12-31",
      "repeatFrequency": "P1W",
      "byDay": [
        "http://schema.org/Friday"
      ],
      "startTime": "18:00Z",
      "endTime": "19:00Z"
    },
  ],
```

Your error message requires that the location of an event is known - which doesn't help for things like online sports events.

**Comment by nickevansuk** [comment]
Ye good point re: online events. There seem to be various schools of thought on this. 2 schedules with different start/end dates requires the data publisher to have the dates of DST for each local timezone stored locally... most discussions regarding this seem to converge here: https://youtu.be/-5wpm-gesOY

Local time avoids these issues, but does present a challenge for virtual events
