### ISSUE TITLE
Data quality rule to check Discussion link in dataset site

### ISSUE THREAD

**Issue by nickevansuk** [openactive/data-model-validator#417]
Validator should check that the discussion link in the dataset site resolves to a valid GitHub issues board (rather than just the repo, or some other location)

**Comment by lukehesluke** [comment]
@nickevansuk The [Dataset API Discovery spec](https://openactive.io/dataset-api-discovery/EditorsDraft/#embedded-json) states, for `discussionUrl`:

> Typically, although not necessarily, this will be a link to a GitHub repository

I suppose, in theory, it seems like non-GitHub repos should be supported (e.g. let's say a GitLab issues board or something else).

It would be useful to know what the impact of not doing this is?

If it seems like a useful thing to do, we could do something like:

* If it's a GH link, flag error if it's not an issues link
* Otherwise, flag warning that this is not a recognised type of discussion link

(Although I understand this is quite a weak set of rules)

**Comment by nickevansuk** [comment]
Great point, and agreed we can't fail on anything that isn't in the spec.

Your suggestion makes sense to me:
- If it's a GH link, flag error if it's not an issues link
- Otherwise, flag warning that this is not a recognised type of discussion link
